/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Estudiante;
import modelo.IConstants;


/**
 *
 * @author dark1
 */
public class ConsultarEstudiantes extends javax.swing.JDialog implements IConstants{
    

    /**
     * Creates new form ConsultarEstudiantesQueCompletaronHorasONo
     */
    public ConsultarEstudiantes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbl_consultarEstudiantes = new javax.swing.JLabel();
        btn_consultar = new rojeru_san.RSButtonRiple();
        btn_atras = new rojeru_san.RSButtonRiple();
        cmbx_consultar = new rojerusan.RSComboMetro();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_tabla = new rojerusan.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lbl_consultarEstudiantes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_consultarEstudiantes.setForeground(new java.awt.Color(0, 153, 51));
        lbl_consultarEstudiantes.setText("Consultar Estudiantes");

        btn_consultar.setBackground(new java.awt.Color(0, 153, 51));
        btn_consultar.setText("Consultar");
        btn_consultar.setBorderPainted(false);
        btn_consultar.setColorHover(new java.awt.Color(0, 102, 51));
        btn_consultar.setFocusPainted(false);
        btn_consultar.setFocusable(false);
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        btn_atras.setBackground(new java.awt.Color(0, 153, 51));
        btn_atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/round_arrow_back_white_18dp.png"))); // NOI18N
        btn_atras.setBorderPainted(false);
        btn_atras.setColorHover(new java.awt.Color(0, 102, 51));
        btn_atras.setFocusPainted(false);
        btn_atras.setFocusable(false);
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });

        cmbx_consultar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Horas Completadas", "Con Horas en Proceso" }));
        cmbx_consultar.setColorArrow(new java.awt.Color(0, 153, 51));
        cmbx_consultar.setColorBorde(new java.awt.Color(0, 153, 51));
        cmbx_consultar.setColorFondo(new java.awt.Color(0, 153, 51));
        cmbx_consultar.setFocusable(false);

        jTable_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cédula", "Nombre", "Correo", "Teléfono", "Lugar", "Horas"
            }
        ));
        jTable_tabla.setColorBackgoundHead(new java.awt.Color(0, 153, 51));
        jTable_tabla.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        jTable_tabla.setColorFilasForeground1(new java.awt.Color(0, 153, 51));
        jTable_tabla.setColorFilasForeground2(new java.awt.Color(0, 153, 51));
        jTable_tabla.setColorSelBackgound(new java.awt.Color(0, 153, 51));
        jScrollPane1.setViewportView(jTable_tabla);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cmbx_consultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_atras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lbl_consultarEstudiantes)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_atras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_consultarEstudiantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbx_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed

        String consulta = (String) cmbx_consultar.getSelectedItem();

        int posicion = 0;
        ArrayList<Estudiante> listaEstudiantes = Controlador.getSingletonInstance().getListaEstudiantesRegistrados();
        ArrayList<Estudiante> listaEstudiantesImprimir = new ArrayList<>();
        switch (consulta) {
            case "Todos":
                listaEstudiantesImprimir.addAll(listaEstudiantes);
                break;

            case "Horas Completadas":
                for (Estudiante estudiante : listaEstudiantes) {
                    if (estudiante.getCantidadHorasCompletadas() == HORAS_DE_SERVICIO) {
                        listaEstudiantesImprimir.add(estudiante);
                    }
                }

                break;
            case "Con Horas en Proceso":
                for (Estudiante estudiante : listaEstudiantes) {
                    if (estudiante.getCantidadHorasCompletadas() < HORAS_DE_SERVICIO) {
                        listaEstudiantesImprimir.add(estudiante);
                    }
                }
                break;

        }
        String data[][] = new String[listaEstudiantesImprimir.size()][6];
        for (Estudiante estudiante : listaEstudiantesImprimir) {
            data[posicion][0] = String.valueOf(estudiante.getCedula());
            data[posicion][1] = estudiante.getNombre();
            data[posicion][2] = estudiante.getCorreo();
            data[posicion][3] = String.valueOf(estudiante.getTelefono());
            data[posicion][4] = Controlador.getSingletonInstance().getGestorEstudiantes().
                    obtenerLugar(estudiante.getLugarServicioSocial());
            data[posicion][5] = String.valueOf(estudiante.getCantidadHorasCompletadas());
            posicion++;
        }

        String columnas[] = {"Cédula", "Nombre", "Correo", "Teléfono", "Lugar", "Horas"};
        jTable_tabla.setModel(new DefaultTableModel(data, columnas));
    }//GEN-LAST:event_btn_consultarActionPerformed

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
    this.dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_btn_atrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultarEstudiantes dialog = new ConsultarEstudiantes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple btn_atras;
    private rojeru_san.RSButtonRiple btn_consultar;
    private rojerusan.RSComboMetro cmbx_consultar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSTableMetro jTable_tabla;
    private javax.swing.JLabel lbl_consultarEstudiantes;
    // End of variables declaration//GEN-END:variables
}
