/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import controlador.Controlador;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author dark1
 */
public class RegistrarEstudiante extends javax.swing.JDialog {

    /**
     * Creates new form RegistrarEstudiante
     */
    public RegistrarEstudiante(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        checkB_universidadPublica.setActivado(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSButtonRiple1 = new rojeru_san.RSButtonRiple();
        PanelNegro = new javax.swing.JPanel();
        PanelBlanco = new javax.swing.JPanel();
        lbl_registrarEstudiante = new javax.swing.JLabel();
        btn_registrar = new rojeru_san.RSButtonRiple();
        txt_nombre = new rojeru_san.RSMTextFull();
        txt_cedula = new rojeru_san.RSMTextFull();
        txt_correoEstudiante = new rojeru_san.RSMTextFull();
        txt_telefono = new rojeru_san.RSMTextFull();
        txt_carrera = new rojeru_san.RSMTextFull();
        checkB_universidadPublica = new rojerusan.RSSwitch();
        lbl_universidadPublica = new javax.swing.JLabel();
        txt_universidad_P_P = new rojeru_san.RSMTextFull();
        btn_atras = new rojeru_san.RSButtonRiple();
        lbl_error = new javax.swing.JLabel();
        txt_direccion = new rojeru_san.RSMTextFull();

        rSButtonRiple1.setText("rSButtonRiple1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanelNegro.setBackground(new java.awt.Color(51, 51, 51));

        PanelBlanco.setBackground(new java.awt.Color(255, 255, 255));

        lbl_registrarEstudiante.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_registrarEstudiante.setForeground(new java.awt.Color(0, 153, 51));
        lbl_registrarEstudiante.setText("Registrar Estudiante");

        btn_registrar.setBackground(new java.awt.Color(0, 153, 51));
        btn_registrar.setText("Registar");
        btn_registrar.setColorHover(new java.awt.Color(0, 102, 51));
        btn_registrar.setFocusPainted(false);
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });

        txt_nombre.setForeground(new java.awt.Color(0, 153, 51));
        txt_nombre.setBordeColorFocus(new java.awt.Color(0, 153, 51));
        txt_nombre.setBotonColor(new java.awt.Color(0, 153, 51));
        txt_nombre.setPlaceholder("Nombre");

        txt_cedula.setForeground(new java.awt.Color(0, 153, 51));
        txt_cedula.setBordeColorFocus(new java.awt.Color(0, 153, 51));
        txt_cedula.setBotonColor(new java.awt.Color(0, 153, 51));
        txt_cedula.setPlaceholder("Cédula");

        txt_correoEstudiante.setForeground(new java.awt.Color(0, 153, 51));
        txt_correoEstudiante.setBordeColorFocus(new java.awt.Color(0, 153, 51));
        txt_correoEstudiante.setBotonColor(new java.awt.Color(0, 153, 51));
        txt_correoEstudiante.setPlaceholder("Correo");

        txt_telefono.setForeground(new java.awt.Color(0, 153, 51));
        txt_telefono.setBordeColorFocus(new java.awt.Color(0, 153, 51));
        txt_telefono.setBotonColor(new java.awt.Color(0, 153, 51));
        txt_telefono.setPlaceholder("Teléfono");

        txt_carrera.setForeground(new java.awt.Color(0, 153, 51));
        txt_carrera.setBordeColorFocus(new java.awt.Color(0, 153, 51));
        txt_carrera.setBotonColor(new java.awt.Color(0, 153, 51));
        txt_carrera.setPlaceholder("Carrera");

        checkB_universidadPublica.setActivado(false);
        checkB_universidadPublica.setColorFondoActivado(new java.awt.Color(0, 153, 51));
        checkB_universidadPublica.setFocusable(false);
        checkB_universidadPublica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkB_universidadPublicaMouseClicked(evt);
            }
        });

        lbl_universidadPublica.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_universidadPublica.setForeground(new java.awt.Color(0, 153, 51));
        lbl_universidadPublica.setText("Universidad Pública");

        txt_universidad_P_P.setForeground(new java.awt.Color(0, 153, 51));
        txt_universidad_P_P.setBordeColorFocus(new java.awt.Color(0, 153, 51));
        txt_universidad_P_P.setBotonColor(new java.awt.Color(0, 153, 51));
        txt_universidad_P_P.setPlaceholder("Correo Institucional");
        txt_universidad_P_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_universidad_P_PActionPerformed(evt);
            }
        });

        btn_atras.setBackground(new java.awt.Color(0, 153, 51));
        btn_atras.setColorHover(new java.awt.Color(255, 255, 255));
        btn_atras.setFocusPainted(false);

        txt_direccion.setForeground(new java.awt.Color(0, 153, 51));
        txt_direccion.setBordeColorFocus(new java.awt.Color(0, 153, 51));
        txt_direccion.setBotonColor(new java.awt.Color(0, 153, 51));
        txt_direccion.setPlaceholder("Dirección");

        javax.swing.GroupLayout PanelBlancoLayout = new javax.swing.GroupLayout(PanelBlanco);
        PanelBlanco.setLayout(PanelBlancoLayout);
        PanelBlancoLayout.setHorizontalGroup(
            PanelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBlancoLayout.createSequentialGroup()
                .addGroup(PanelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBlancoLayout.createSequentialGroup()
                        .addGroup(PanelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelBlancoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btn_atras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(lbl_registrarEstudiante))
                            .addGroup(PanelBlancoLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(PanelBlancoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_cedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_correoEstudiante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_telefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_carrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PanelBlancoLayout.createSequentialGroup()
                                .addComponent(txt_universidad_P_P, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(40, 40, 40))
                            .addComponent(txt_direccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(23, 23, 23))
            .addGroup(PanelBlancoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBlancoLayout.createSequentialGroup()
                        .addComponent(lbl_universidadPublica)
                        .addGap(18, 18, 18)
                        .addComponent(checkB_universidadPublica, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbl_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelBlancoLayout.setVerticalGroup(
            PanelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBlancoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_atras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_registrarEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_correoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(checkB_universidadPublica, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_universidadPublica, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(txt_universidad_P_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_error, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout PanelNegroLayout = new javax.swing.GroupLayout(PanelNegro);
        PanelNegro.setLayout(PanelNegroLayout);
        PanelNegroLayout.setHorizontalGroup(
            PanelNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNegroLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(PanelBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        PanelNegroLayout.setVerticalGroup(
            PanelNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNegroLayout.createSequentialGroup()
                .addComponent(PanelBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelNegro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelNegro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_universidad_P_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_universidad_P_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_universidad_P_PActionPerformed

    private void checkB_universidadPublicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkB_universidadPublicaMouseClicked
        if (checkB_universidadPublica.isActivado()) {
            txt_universidad_P_P.setPlaceholder("Correo Institucional");
        }else{
            txt_universidad_P_P.setPlaceholder("Dinero requerido");
        }
    }//GEN-LAST:event_checkB_universidadPublicaMouseClicked

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        boolean error = false;
        String mensajeError = "";
        lbl_error.setText("");
        ArrayList<String> listaDatos = new ArrayList<>();
        listaDatos.add(txt_carrera.getText());
        listaDatos.add(txt_cedula.getText());
        listaDatos.add(txt_correoEstudiante.getText());
        listaDatos.add(txt_universidad_P_P.getText());
        listaDatos.add(txt_nombre.getText());
        listaDatos.add(txt_telefono.getText());
        if (!Controlador.getSingletonInstance().getValidacion().validarDatoVacio(listaDatos)) {
            mensajeError += "No se debe dejar espacios en blanco.\n";
            lbl_error.setText(mensajeError);
        }else{
            if (!Controlador.getSingletonInstance().getValidacion().validarCedula(txt_cedula.getText())) {
                mensajeError += "La cédula debe contener 10 dígitos.\n";
                lbl_error.setText(mensajeError);
                error = true;
            }
            if (!Controlador.getSingletonInstance().getValidacion().validarCorreo(txt_correoEstudiante.getText())) {
                mensajeError += "El correo del estudiante no es válido.\n";
                lbl_error.setText(mensajeError);
                error = true;
            }
            if (!Controlador.getSingletonInstance().getValidacion().validarTelefono(txt_telefono.getText())) {
                mensajeError += "El teléfono debe contener 8 dígitos.\n";
                lbl_error.setText(mensajeError);
                error = true;
            }

            if (checkB_universidadPublica.isActivado()) {
                if (!Controlador.getSingletonInstance().getValidacion().validarCorreo(txt_universidad_P_P.getText())) {
                    mensajeError += "El correo institucional no es válido.\n";
                    lbl_error.setText(mensajeError);
                    error = true;
                }
            }else{
                if (!Controlador.getSingletonInstance().getValidacion().validarDigitosDobles(txt_universidad_P_P.getText())) {
                    mensajeError += "El monto que ingresó no es válido.\n";
                    lbl_error.setText(mensajeError);
                    error = true;
                }
            }
            if (!error) {
                if (!Controlador.getSingletonInstance().getGestorEstudiantes().registrarEstudiante(txt_carrera.getText(),
                    txt_cedula.getText(), txt_correoEstudiante.getText(), txt_nombre.getText(), txt_telefono.getText(),
                    txt_universidad_P_P.getText(), checkB_universidadPublica.isActivado(), txt_direccion.getText())) {
                mensajeError += "El estudiante ya está registrado.\n";
                lbl_error.setText(mensajeError);
            }else{
                JOptionPane.showMessageDialog(this, "Se registró correctamente al estudiante.", "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        }
        

        }
    }//GEN-LAST:event_btn_registrarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistrarEstudiante dialog = new RegistrarEstudiante(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBlanco;
    private javax.swing.JPanel PanelNegro;
    private rojeru_san.RSButtonRiple btn_atras;
    private rojeru_san.RSButtonRiple btn_registrar;
    private rojerusan.RSSwitch checkB_universidadPublica;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JLabel lbl_registrarEstudiante;
    private javax.swing.JLabel lbl_universidadPublica;
    private rojeru_san.RSButtonRiple rSButtonRiple1;
    private rojeru_san.RSMTextFull txt_carrera;
    private rojeru_san.RSMTextFull txt_cedula;
    private rojeru_san.RSMTextFull txt_correoEstudiante;
    private rojeru_san.RSMTextFull txt_direccion;
    private rojeru_san.RSMTextFull txt_nombre;
    private rojeru_san.RSMTextFull txt_telefono;
    private rojeru_san.RSMTextFull txt_universidad_P_P;
    // End of variables declaration//GEN-END:variables
}
